# Cost-Efficient Cloud Build for MVP/Demo
# Uses Deep Infra API instead of local PyTorch models
# ~75% cost reduction, ~90% faster builds, ~93% faster cold starts
#
# Usage: gcloud builds submit --config=cloudbuild-deploy-mvp.yaml

steps:
  # Build all images in parallel (no model fetch needed)
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-f'
      - './services/rag/Dockerfile.deepinfra'
      - '-t'
      - 'gcr.io/$PROJECT_ID/rag-service:latest'
      - './services/rag'
    id: 'build-rag'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/planner-service:latest', './services/planner']
    id: 'build-planner'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/quiz-service:latest', './services/quiz']
    id: 'build-quiz'
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/gateway:latest', './gateway']
    id: 'build-gateway'
  
  # Push all images to GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/rag-service:latest']
    id: 'push-rag'
    waitFor: ['build-rag']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/planner-service:latest']
    id: 'push-planner'
    waitFor: ['build-planner']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/quiz-service:latest']
    id: 'push-quiz'
    waitFor: ['build-quiz']
  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/gateway:latest']
    id: 'push-gateway'
    waitFor: ['build-gateway']
  
  # Deploy RAG Service (lightweight Deep Infra version)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'rag-service'
      - '--image=gcr.io/$PROJECT_ID/rag-service:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=60'
      - '--concurrency=20'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-secrets=DATABASE_URL=database-url:latest,QDRANT_URL=qdrant-url:latest,QDRANT_API_KEY=qdrant-api-key:latest,DEEPINFRA_API_KEY=deepinfra-api-key:latest,AWS_ACCESS_KEY_ID=aws-access-key-id:latest,AWS_SECRET_ACCESS_KEY=aws-secret-access-key:latest,AWS_REGION=aws-region:latest,S3_BUCKET_NAME=s3-bucket-name:latest'
      - '--set-env-vars=USE_DEEPINFRA=true,DEEPINFRA_BASE_URL=https://api.deepinfra.com/v1,DEEPINFRA_EMBEDDING_MODEL=intfloat/e5-base-v2,DEEPINFRA_RERANKER_MODEL=Qwen/Qwen3-Reranker-0.6B,QDRANT_COLLECTION=resources,LOG_LEVEL=info'
    id: 'deploy-rag'
    waitFor: ['push-rag']
  
  # Deploy Planner Service (reduced resources)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RAG_URL=$$(gcloud run services describe rag-service --region=${_REGION} --format="value(status.url)")
        gcloud run deploy planner-service \
          --image=gcr.io/$PROJECT_ID/planner-service:latest \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=512Mi \
          --cpu=1 \
          --timeout=300 \
          --concurrency=20 \
          --min-instances=0 \
          --max-instances=5 \
          --set-secrets=DATABASE_URL=database-url:latest,OPENROUTER_API_KEY=openrouter-api-key:latest \
          --set-env-vars=RAG_SERVICE_URL=$$RAG_URL,LLM_MODEL=anthropic/claude-3.5-sonnet,LOG_LEVEL=info
    id: 'deploy-planner'
    waitFor: ['push-planner', 'deploy-rag']
  
  # Deploy Quiz Service (reduced resources)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'quiz-service'
      - '--image=gcr.io/$PROJECT_ID/quiz-service:latest'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--timeout=300'
      - '--concurrency=20'
      - '--min-instances=0'
      - '--max-instances=5'
      - '--set-secrets=DATABASE_URL=database-url:latest,OPENROUTER_API_KEY=openrouter-api-key:latest,SUPABASE_URL=supabase-url:latest,SUPABASE_SERVICE_KEY=supabase-service-key:latest,AWS_ACCESS_KEY_ID=aws-access-key-id:latest,AWS_SECRET_ACCESS_KEY=aws-secret-access-key:latest,AWS_REGION=aws-region:latest,S3_BUCKET_NAME=s3-bucket-name:latest'
      - '--set-env-vars=LLM_MODEL=anthropic/claude-3.5-sonnet,LOG_LEVEL=info'
    id: 'deploy-quiz'
    waitFor: ['push-quiz']
  
  # Deploy Gateway
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        RAG_URL=$$(gcloud run services describe rag-service --region=${_REGION} --format="value(status.url)")
        PLANNER_URL=$$(gcloud run services describe planner-service --region=${_REGION} --format="value(status.url)")
        QUIZ_URL=$$(gcloud run services describe quiz-service --region=${_REGION} --format="value(status.url)")
        gcloud run deploy gateway \
          --image=gcr.io/$PROJECT_ID/gateway:latest \
          --region=${_REGION} \
          --platform=managed \
          --allow-unauthenticated \
          --memory=256Mi \
          --cpu=1 \
          --timeout=60 \
          --concurrency=100 \
          --min-instances=0 \
          --max-instances=10 \
          --set-secrets=SUPABASE_URL=supabase-url:latest,SUPABASE_ANON_KEY=supabase-anon-key:latest \
          --set-env-vars="^##^RAG_SERVICE_URL=$$RAG_URL##PLANNER_SERVICE_URL=$$PLANNER_URL##QUIZ_SERVICE_URL=$$QUIZ_URL##JWT_PUBLIC_KEY_URL=https://hywmzhvyhiynewfsmqln.supabase.co/auth/v1/jwks##ALLOWED_ORIGINS=${_ALLOWED_ORIGINS}##RATE_LIMIT_REQUESTS=100##RATE_LIMIT_WINDOW=60##LOG_LEVEL=info"
    id: 'deploy-gateway'
    waitFor: ['push-gateway', 'deploy-rag', 'deploy-planner', 'deploy-quiz']

substitutions:
  _REGION: 'europe-west1'
  _ALLOWED_ORIGINS: 'https://your-app.vercel.app,http://localhost:3000'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'  # 20 minutes (down from 40)
